//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploProjeto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExemploProjeto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de início superior à data de fim.
        /// </summary>
        internal static string MESSAGE_DATA_INICIO_SUPERIOR_DATAFIM {
            get {
                return ResourceManager.GetString("MESSAGE_DATA_INICIO_SUPERIOR_DATAFIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do projeto inválido.
        /// </summary>
        internal static string MESSAGE_DESCRICAO_PROJETO_INVALIDO {
            get {
                return ResourceManager.GetString("MESSAGE_DESCRICAO_PROJETO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error [{0}] to save.
        /// </summary>
        internal static string MESSAGE_ERRO_A_GRAVAR {
            get {
                return ResourceManager.GetString("MESSAGE_ERRO_A_GRAVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar com sucesso.
        /// </summary>
        internal static string MESSAGE_GRAVADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("MESSAGE_GRAVADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID do projeto inválido.
        /// </summary>
        internal static string MESSAGE_ID_PROJETO_INVALIDO {
            get {
                return ResourceManager.GetString("MESSAGE_ID_PROJETO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projecto [{0}] não existe na BD.
        /// </summary>
        internal static string MESSAGE_PROJETO_NAO_EXISTE {
            get {
                return ResourceManager.GetString("MESSAGE_PROJETO_NAO_EXISTE", resourceCulture);
            }
        }
    }
}
